### ISSUE TITLE
It Won't Work

### ISSUE THREAD

**Issue by MOAAAII** [The4codeblocks/sandbox-utilities#1]
I Just get this message every time

![Screenshot_20231027-161102_Mindustry.jpg](https://github.com/The4codeblocks/sandbox-utilities/assets/149203097/883e7c7f-5a16-432c-98e4-1cb67c78d289)

![Screenshot_20231027-161056_Mindustry.jpg](https://github.com/The4codeblocks/sandbox-utilities/assets/149203097/81e74fc3-b4ca-4114-a6d4-bc5c97fd55ad)

```
```
``
```
```

**Comment by The4codeblocks** [comment]
I can fix that

**Comment by The4codeblocks** [comment]
FIXED
